apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: nginx
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/mastercam123/guestbook
      imageSelectionStrategy: SemVer