apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: flask-demo
  namespace: kargo-flask
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/mastercam123/flask-demo
      imageSelectionStrategy: SemVer