apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: flask
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: flask-*
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/mastercam123/kargo-helm.git